site_name: Action System Design
site_url: https://sorenon.github.io/Action-System/
repo_url: https://github.com/Sorenon/Action-System/

theme:
    name: 'material'
    palette:

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

markdown_extensions:
  - footnotes
  - nl2br
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
