name: ci
on:
  push:
    branches:
      - main
      - master
      - trunk
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-drawio-exporter
      - run: mkdocs gh-deploy --force